# Generated by Django 6.0.1 on 2026-01-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todo_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
